# 用户名
spring:
  mail:
    username: 15512702732@163.com
    password: Dzwxszwm1202
    # 发送服务器
    host: smtp.163.com
    # 开启加密授权验证：qq才有
    # properties。mail.smtp.ssl.enable=true
    # 默认协议smtp
    protocol: smtp
